### PR TITLE
rely on official postgres:9.3 image

### PR DESCRIPTION
**Pull request by bacongobbler**

### CODE REVIEW

**Comment by mboersma** [comment]
`3 additions and 364 deletions.` :v: This code LGTM.

**Comment by carmstrong** [comment]
:ship:

**Comment by mboersma** [comment]
Tested locally, seems to work fine. I guess we could just use `postgres:9.3` directly, but LGTM again.

**Comment by bacongobbler** [comment]
We have some [code in the integration tests](https://github.com/deis/deis/blob/master/tests/mock/mock.go#L36) that prevent us from using it directly, which I had to work around via the hook. Otherwise then yes, we could totally use the image directly.

**Pull request merged**
